name: location_assignment
description: "A new Flutter project."

publish_to: 'none'  

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  permission_handler: ^11.3.1
  geolocator: ^13.0.1
  app_settings: ^5.1.1
  get:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
 
flutter:

  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
   